[package]
name = "near"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitmaps = "3.2.0"
near-sdk = {version = "4.1.0-pre.0", features=["unstable"] }